### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aiiddqd** [uptimizt/reactions-emoji#1]
- [x] MVP
- [ ] tests on https://bizzapps.ru/
- [ ] hook for update and changes - for logs or customisation
- [ ] block for Gutenberg
- [ ] option - only for logged users
- [ ] public to wp org
